// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGveGX3quacAxLFCqQdfIN3WGJFBAgwnw',
    appId: '1:582241506381:web:f9bd29672da7bcb15a7804',
    messagingSenderId: '582241506381',
    projectId: 'fitflow-kavidu',
    authDomain: 'fitflow-kavidu.firebaseapp.com',
    storageBucket: 'fitflow-kavidu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDknVKifjch4ze8uhFYibODlwAujnqsxA',
    appId: '1:582241506381:android:2969233d441f025a5a7804',
    messagingSenderId: '582241506381',
    projectId: 'fitflow-kavidu',
    storageBucket: 'fitflow-kavidu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFCS88Oy-1_E_ixZhorwfqa-JPSAtGesE',
    appId: '1:582241506381:ios:9dad70358f5996055a7804',
    messagingSenderId: '582241506381',
    projectId: 'fitflow-kavidu',
    storageBucket: 'fitflow-kavidu.firebasestorage.app',
    iosBundleId: 'com.kavidu.fitflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFCS88Oy-1_E_ixZhorwfqa-JPSAtGesE',
    appId: '1:582241506381:ios:9dad70358f5996055a7804',
    messagingSenderId: '582241506381',
    projectId: 'fitflow-kavidu',
    storageBucket: 'fitflow-kavidu.firebasestorage.app',
    iosBundleId: 'com.kavidu.fitflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGveGX3quacAxLFCqQdfIN3WGJFBAgwnw',
    appId: '1:582241506381:web:afc9b8a7bd9ebc435a7804',
    messagingSenderId: '582241506381',
    projectId: 'fitflow-kavidu',
    authDomain: 'fitflow-kavidu.firebaseapp.com',
    storageBucket: 'fitflow-kavidu.firebasestorage.app',
  );
}
